apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://localhost:6443
  name: fake-cluster
contexts:
- context:
    cluster: fake-cluster
    user: fake-user
    namespace: default
  name: fake-context
current-context: fake-context
users:
- name: fake-user
  user: {}
